FROM astral-sh/uv:0.11 AS uv

FROM python:alpine

ENV PAGERMAID_DIR=/pagermaid
ENV TZ=Asia/Shanghai
ENV SHELL=/bin/bash

WORKDIR /pagermaid/workdir

COPY --from=uv /uv /usr/local/bin/uv
COPY ./ /pagermaid/workdir

RUN apk add --no-cache git bash libmagic curl tzdata libzbar figlet fortune openssl tini fastfetch \
    && apk add --no-cache --update --virtual .build-deps gcc python3-dev musl-dev linux-headers rust cargo \
    && git config --global pull.ff only \
    && uv pip install --system -r requirements.txt \
    && uv cache clean \
    && rm -rf /root/.cargo \
    && apk del .build-deps

ENTRYPOINT ["tini","--","bash","utils/docker-config.sh"]
